### ISSUE TITLE
Issue: The Project upload button is not working

### ISSUE THREAD

**Issue by AstragoYT** [evenstensberg/webpack-ui#30]
I wanted to upload a .config file, but the button didn't work. nothing happend

**Comment by AstragoYT** [comment]
I am a beginner and don't know much about webpack. I might do something wrong

**Comment by rishabh3112** [comment]
Hi @AstragoYT, this project has been abandoned as maintainers.
Meanwhile you may try https://github.com/rishabh3112/webpack-ui, which is feature complete in the sense it is.

**Comment by AstragoYT** [comment]
thank you
